config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/terms', to: 'terms#index'
  get '/about', to: 'about#index'
  get '/faq', to: 'common_questions#index'

  resources :users
  resources :tracker_projects, only: [:show]

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tasks do
    resources :comments

  end

  get 'sign-up', to: 'registration#new'
  post 'sign-up', to: 'registration#create'
  get 'sign-in', to: 'authentication#new', as: 'signin'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  validates :user, :presence => true
  validates :user, uniqueness: {scope: :project_id, message: 'has already been added to this project'}

  belongs_to :user
  belongs_to :project

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_action :auth
  before_action :find_and_set_project
  before_action :limit_actions
  before_action :set_membership, only: [ :show, :edit, :update]
  before_action :ensure_owner_or_admin, only: [:create, :update]
  before_action :ensure_member_or_admin, only: [:create,:update, :destroy]
  before_action :ensure_at_least_one_owner, only: [:update, :destroy]


    def index
      @memberships = @project.memberships
      @membership = @project.memberships.new
      @project_name = @project.name
    end


    def create
      @membership = @project.memberships.new(membership_params)
      if @membership.save
        flash[:notice] = "#{@membership.user.full_name} has been successfully added"
        redirect_to project_memberships_path(@project)
      else
        render :index
      end
    end


    def update
     if owner_count(@project) == 1 && @membership.role == 1
       flash[:danger] = "Projects must have at least one owner"
       redirect_to project_memberships_path(@project.id)
     elsif @membership.update(membership_params)
       redirect_to project_memberships_path(@project.id)
     else
       render :index
     end
   end

    def destroy
      membership = Membership.find(params[:id])
      if Membership.find_by(project_id: @project.id, user_id: current_user.id, role: 1) || current_user.admin || current_user.id == membership.user_id
        membership.destroy
        flash[:notice] = "#{membership.user.full_name} was successfully removed"
        redirect_to projects_path
      else
        flash[:danger] = "You do not have access"
        redirect_to project_path(@project)
      end
    end





private

  def set_membership
     @membership = @project.memberships.find(params[:id])
   end

  def membership_params
    params.require(:membership).permit(:user_id, :project_id, :role)
  end


  def find_and_set_project
    @project = Project.find(params[:project_id])
  end

  def ensure_member_or_admin
    if !current_user.member_admin?(@project)
      flash[:danger] = 'You do not have access'
      redirect_to projects_path
    end
  end

  def ensure_at_least_one_owner
    if owner_count(@project)==1 && Membership.find(params[:id]).role == 1
      flash[:danger] = 'Projects much have at least one owner'
      redirect_to project_memberships_path(@project)
    end
  end

  def ensure_owner_or_admin
    if !current_user.owner_admin?(@project)
      flash[:danger] = 'You do not have access'
      redirect_to projects_path
    end
  end
end

app/views/memberships/_form.html.erb
<%= form_for [@membership.project, @membership], html: {class: 'form-inline'} do |f| %>
<%= f.collection_select(:user_id, User.all, :id, :full_name, {include_blank: 'Please select user'}, {class: 'form-control'}) %>
<%= f.select(:role, [['Owner', 1], ['Member', 2]], {}, {class: 'form-control'}) %>
<%= f.submit "Add New Member", class: 'btn btn-info' %>
<% end %>

app/views/memberships/index.html.erb
<div class="page-header">
  <h1>
    <%= "#{@project.name}: Manage Members" %>
  </h1>
</div>
<ol class = "breadcrumb">
  <li> <%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %> </li>
  <li>Memberships</li>
</ol>

<% if @membership.errors.any? %>
<div class="row">
  <div class ="col-sm-6">
    <div class = "alert alert-danger">

      <h3><%= pluralize(@membership.errors.count, "error")%>  prohibited this from being saved : </h3>
      <ul>
        <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>


<div class "col-md-8">
  <% if Membership.find_by(project_id: @project.id, user_id: current_user.id, role: 1) || current_user.admin %>
    <div class="well">
      <%= render "form" %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-5">
      <table class="table">
        <% @project.memberships.each do |membership| %>
          <% if membership.user.present? && membership.id.present? %>
            <%= form_for [@project, membership], html: {class: 'form-inline'} do |f| %>
              <tr>
                <% if Membership.find_by(project_id: @project.id, user_id: current_user.id, role: 1) || current_user.admin %>
                  <td><%= link_to membership.user.full_name, user_path(membership.user), class: "pull-left" %></td>
                  <td><%= f.select(:role, [['Owner',1], ['Member', 2]], {}, {class: 'form-control'}) %></td>
                  <td><%= f.submit 'Update', class: "btn btn-info"  %></td>

                  <% if membership.role==1 && owner_count(@project)==1 && membership.user==current_user  %>
                      <td> You are the last owner</td>
                    <% else %>
                  <td><%= link_to "", project_membership_path(@project,membership), method: :delete, class: "glyphicon glyphicon-remove" %></td>
                      <% end %>

                <% else %>
                  <td><%= link_to membership.user.full_name, user_path(membership.user) %></td>
                  <% if membership.role == 1 %>
                  <td> owner </td>
                  <% else %>
                  <td>member</td>
                  <% end %>
                  <% if current_user == membership.user %>
                    <td><%= link_to "", project_membership_path(@project,membership), method: :delete, class: "glyphicon glyphicon-remove" %></td>
                  <% else %>
                    <td></td>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>