config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/terms', to: 'terms#index'
  get '/about', to: 'about#index'
  get '/faq', to: 'common_questions#index'

  resources :users
  resources :tracker_projects, only: [:show]

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tasks do
    resources :comments

  end

  get 'sign-up', to: 'registration#new'
  post 'sign-up', to: 'registration#create'
  get 'sign-in', to: 'authentication#new', as: 'signin'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true

  belongs_to :project
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :auth
  before_action :find_and_set_project
  before_action :limit_actions

  def index
    @tasks = @project.tasks
  end


  def new
    @task = @project.tasks.new
  end



  def create
    @task = @project.tasks.new(task_params)

    if @task.save
      flash[:notice] = "Task was successfully created"
      redirect_to project_task_path(@project, @task)
    else
      render:new
    end
  end


  def show
    @task = @project.tasks.find(params[:id])
    @comment = Comment.new
  end



  def edit
@task = Task.find(params[:id])
  end


  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      flash[:notice] = "Task was successfully updated"
      redirect_to project_task_path(@project, @task)
    else
      render :edit
    end
  end


  def destroy
    task = @project.tasks.find(params[:id])
    task.destroy
    redirect_to project_tasks_path
  end



  private

  def task_params
    params.require(:task).permit(:description, :complete, :date, :project_id)
  end

  def find_and_set_project
    @project = Project.find(params[:project_id])
  end


end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
<%= render partial: "/shared/errors", locals:{object: @task} %>
<div class ="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
   <div class = "col-sm-4">
    <%= f.text_field :description, class:"form-control" %>
  </div>
</div>

<div class ="form-group">
   <%= f.label :date, "Due Date", class: "col-sm-2 control-label" %>
  <div class = "col-sm-4">
    <%= f.date_field :date, class: "col-sm-4 form-control" %>
  </div>
</div>

<div class="form-group">
 <div class = "col-md-offset-2 col-md-10">
   <%= f.check_box :complete %>
   <%= f.label :complete %>
 </div>
 </div>


<div class ="form-group">
  <div class = "col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', project_tasks_path, class: "btn btn-default" %>
  </div>
</div>

<% end %>

app/views/tasks/edit.html.erb
    <div class = "page-header">
      <h1>
        Edit Task
      </h1>
    </div>
    <div class="form-horizontal">
      <ol class="breadcrumb">
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to @project.name, project_path(@project) %></li>
        <li><%= link_to "Tasks", project_tasks_path %></li>
        <li><%=link_to @task.description, project_task_path(@project, @task) %></li>
        <li class="active">Edit</li>
      </ol>

  <%= render "form" %>
</div>

app/views/tasks/index.html.erb
    <div class = "page-header">
        <%= link_to 'New Task', new_project_task_path, class: "btn btn-info pull-right" %>
        <h1>Tasks for <%= @project.name %> </h1>
    </div>
    <ol class = "breadcrumb">
    <li><%= link_to "Projects", projects_path %> / <%= link_to @project.name, project_path(@project) %> / Tasks</li>
    </ol>

    <table class = "table">
        <thead>
        <tr>
          <div class = "col-sm-1">
            <th>Description</th>
          </div>
          <div class = "col-sm-3">
          <th>Due On</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
        <tr>
          <% if task.complete %>
              <td class = "col-sm-3">
                <s><%= link_to task.description, project_task_path( @project, task) %></s></td>
          <% else %>
              <td><%= link_to task.description, project_task_path( @project, task) %>
              <%= link_to task.comments.count, project_task_path( @project, task), class: "badge" %></td>

          <% end %>
              <td><% if task.date %>
                    <%= task.date.strftime("%m/%d/%Y") %>
                    <% end %>
              </td>

             <td>
          <div class = "pull-right">
            <%= link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info" %>
            <%= link_to ' ', project_task_path(@project, task), method: :delete, class: "glyphicon glyphicon-remove" %>
          </div>
         </td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/tasks/new.html.erb
  <div class = "page-header">
    <h1>New Task</h1>
  </div>
  <div class="form-horizontal">
  <ol class="breadcrumb">
    <li><%= link_to "Tasks", project_tasks_path %></li>
    <li class="active">New Task</li>
  </ol>
<%= render "form" %>

app/views/tasks/show.html.erb
  <div class= 'page-header'>
    <div class="pull-right">
        <%= link_to "Edit", edit_project_task_path(@project,@task), class: "btn btn-info" %>
    </div>
    <% if @task.complete == true %>
      <h1><s><%= @task.description %></s></h1>
    <% else %>
      <h1><%= @task.description %></h1>
    <% end %>
  </div>

  <div class="form-horizontal">
    <ol class="breadcrumb">
      <li><%= link_to "Projects", projects_path%></li>
      <li><%= link_to @project.name, project_path(@project) %></li>
      <li><%= link_to "Tasks", project_tasks_path( @project )%></li>
      <li><%= @task.description %></li>

    </ol>
  </div>

  <% if @task.date %>
    <strong>Due On:</strong>
    <%= @task.date.strftime("%m/%d/%Y") %>
  <% end %>


  <h3>Comments</h3>
  <% @task.comments.each do |comment| %>
    <p>
      <div class = "row">
        <div class = "col-md-3">
          <% if comment.user_id %>
            <%= link_to comment.user.full_name, user_path(comment.user) %>
          <% else %>
            <p>(deleted user)</p>
          <% end %>
          <div class = "text-muted">
            <%= time_ago_in_words(comment.created_at) + " ago" %>
          </div>
        </div>
        <div class= "col-md-9 pull-right">
          <%= comment.content %>
        </div>
      </div>
    </p>
  <% end %>


  <%= form_for [@task, @comment] do |f|%>
    <div class = "form-group">
      <div class="col-sm-offset-3 col-md-9">
          <div class = "form-group">
            <%= f.text_area :content, class: "form-control" %>
          </div>
          <p><%= f.submit "Add Comment", class: "btn btn-info" %></p>
      </div>
    </div>
  <% end %>