config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/terms', to: 'terms#index'
  get '/about', to: 'about#index'
  get '/faq', to: 'common_questions#index'

  resources :users
  resources :tracker_projects, only: [:show]

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tasks do
    resources :comments

  end

  get 'sign-up', to: 'registration#new'
  post 'sign-up', to: 'registration#create'
  get 'sign-in', to: 'authentication#new', as: 'signin'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

has_many :tasks

has_many :tasks, dependent: :destroy
has_many :memberships, dependent: :destroy
has_many :users, through: :memberships
has_many :comments, through: :tasks

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :auth
  before_action :set_project, only: [:edit, :show, :update, :destroy]
  before_action :project_owner_auth, only: [:edit, :update, :destroy]
  before_action :project_member_auth, only: [ :edit, :update, :destroy]

  def index
    @projects = Project.all
    tracker_api = TrackerAPI.new
    if current_user.pivotal_token
      if tracker_api.projects(current_user.pivotal_token).class == Array
        @tracker_projects = tracker_api.projects(current_user.pivotal_token)
      else
        flash[:danger] = 'Pivotal Tracker Token Invalid'
        @tracker_projects = []
      end
    end
  end


  def new
    @project = Project.new
  end


    def create
      @project = Project.new(project_params)
      if @project.save
        flash[:notice] = 'Project was successfully created'
        redirect_to project_tasks_path(@project)
        @project.memberships.create!(role: 1, user_id: current_user.id)
      else
        render :new
      end
    end


  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end


  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = 'Project was successfully updated'
      redirect_to project_path(@project)
    else
      render :edit
    end
  end



  def destroy
    project = Project.find(params[:id])
    project.destroy
      flash[:notice] = 'Project was successfully deleted'
      redirect_to projects_path
  end



  private

  def set_project
    @project=Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :pivotal_token)
  end

  def project_owner_auth
    unless Membership.where(project_id: @project.id).include?(current_user.memberships.find_by(role: 1)) || current_user.admin
      flash[:danger] = "You do not have access to that project"
      redirect_to projects_path
    end
  end

  def project_member_auth
    unless current_user.projects.include?(@project) || current_user.admin
      flash[:danger] = "You do not have access to that project"
      redirect_to project_path(@project)
    end
  end



end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<%= render partial: "/shared/errors", locals:{object: @project} %>
<div class ="form-group">
  <%= f.label :name, class: "col-sm-2 control-label" %>
 <div class = "col-sm-5">
  <%= f.text_field :name, class: "col-sm-8 form-control" %>
  </div>
</div>

<div class ="form-group">
  <div class = "col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', projects_path, class: "btn btn-default" %>
  </div>
</div>

<% end %>

app/views/projects/edit.html.erb
<div class = "page-header">
   <h1>
    Edit Project
  </h1>
</div>


<ol class="breadcrumb">
  <li><%= link_to 'Projects', projects_path %></li>
  <li><%= link_to @project.name, projects_path %></li>
  <li>Edit</li>
</ol>

<div class="form-horizontal">
  <%= render "form" %>
</div>

app/views/projects/index.html.erb
    <div class = "page-header">
      <div class = "pull-right">
        <%= link_to 'New Project', new_project_path, class: "btn btn-info" %>
      </div>
      <h1>Projects</h1>
    </div>

    <table class = "table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Tasks</th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.admin == true %>
            <% @projects.each do |project| %>
            <tr>
              <td class = "col-sm-4"><%= link_to project.name, project_path(project) %></td>
              <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
            </tr>
            <% end %>
        <%else%>
          <% current_user.projects.each do |project| %>
          <tr>
            <td class = "col-sm-4"><%= link_to project.name, project_path(project) %></td>
            <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <% if @tracker_projects %>
      <h1 class = "page-header">
        Pivotal Tracker Projects
      </h1>
      <table class="table">
        <thead>
          <th> Name </th>
        </thead>

        <% @tracker_projects.each do |tracker_project| %>
          <tr>
            <% tracker_id = tracker_project[:id] %>
            <td><%= link_to tracker_project[:name], "tracker_projects/#{tracker_project[:id]}" %></td>
          </tr>
        <% end %>
      </table>
    <% end %>

app/views/projects/new.html.erb
<div class = "page-header">
  <h1>New Project</h1>
</div>
<ol class="breadcrumb">
<li><%= link_to 'Projects', projects_path %></li>
<li>New</li>
</ol>
<div class="form-horizontal">
  <%= render "form" %>
</div>

app/views/projects/show.html.erb
<div class= "page-header">
  <div class="pull-right">
    <% if Membership.where(project_id: @project.id).include?(current_user.memberships.find_by(role: 1)) || current_user.admin %>
      <%= link_to 'Edit', edit_project_path(@project), class:"btn btn-info" %>
    <% end %>
  </div>
  <h1>
    <%= @project.name %>
  </h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to 'Projects', projects_path %></li>
  <li><%= @project.name %></li>
</ol>
  <%= link_to pluralize(@project.tasks.count, 'Task') , project_tasks_path(@project) %>

<div>
  <%= link_to pluralize(@project.memberships.count, 'Membership') , project_memberships_path(@project) %>
</div>
<br>
<% if Membership.where(project_id: @project.id).include?(current_user.memberships.find_by(role: 1)) || current_user.admin %>
  <div class = "well">
    <h3>Delete Project</h3>
    <%= "Deleting this project will delete #{pluralize(@project.memberships.count, 'membership')}, #{pluralize(@project.tasks.count, 'task')} and associated comments." %>
    <br><br>
    <div>
      <%= link_to 'Delete', project_path,method: :delete, data: {confirm: "Are you sure?"},class:"btn btn-danger" %>
    </div>
  </div>
<% end %>